export const ROUTES = {
  root: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  dashboard: "/operations/dashboard",
  orders: "/operations/orders",
  quotations: "/operations/quotations",
  operationsInvoices: "/operations/invoices",
  products: "/operations/products",
  pricing: "/operations/pricing",
  schedule: "/operations/schedule",
  reports: "/operations/reports",
  settings: "/operations/settings",
  catalog: "/portal/catalog",
  productDetail: "/portal/catalog/:productId",
  cart: "/portal/cart",
  checkout: "/portal/checkout",
  checkoutPayment: "/portal/checkout/payment",
  checkoutSuccess: "/portal/checkout/success",
  customerOrders: "/portal/orders",
  customerInvoices: "/portal/invoices",
  wishlist: "/portal/wishlist",
  profile: "/portal/profile",
  customerSettings: "/portal/settings",
  notFound: "*",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
